#!/usr/bin/env python
import mailbox

src = '/home/nelhage/OracleMail/INBOX'
dst = '/home/nelhage/OracleMail/Termination'

srcmd = mailbox.Maildir(src, factory=None)
dstmd = mailbox.Maildir(dst, factory=None)

termination_addr = '<daily_termination_notices_any_ww@oracle.com>'

for k in srcmd.keys():
    msg = srcmd[k]
    if termination_addr in msg.get('Cc', '').lower() or \
            termination_addr in msg.get('To', '').lower():
        dstmd.add(msg)
        srcmd.remove(k)
