#!/usr/bin/env python
import os
import sys
import socket

host = 'google.com'
port = 80
if len(sys.argv) > 1:
    host = sys.argv[1]
    if len(sys.argv) > 2:
        port = sys.argv[2]

s = socket.socket()
s.connect((host, port))
print s.getsockname()[0]
