#!/bin/bash

main=origin/main
if ! git rev-parse -q --verify "$main"; then
    main=origin/master
fi

heads=$(git worktree list --porcelain | awk '/branch/ {print $2}')

eval "$(git for-each-ref refs/heads/ --merged $main --shell --format='
set -eu
ref=%(refname)
sha=%(objectname)
shortref=%(refname:short)
shortsha=%(objectname:short)
if ! echo "$heads" | grep -Fq "$ref"; then
    git update-ref -d "$ref" "$sha"
    echo "Deleted $shortref ($shortsha)"
fi
')"
