#!/bin/bash
set -eu

if ! main=$(git rev-parse --abbrev-ref refs/remotes/origin/HEAD 2>/dev/null); then
    main=origin/main
    if ! git rev-parse -q --verify "$main"; then
        main=origin/master
    fi
fi

heads=$(git worktree list --porcelain | awk '/branch/ {print $2}')


eval "$(git for-each-ref refs/heads/ --merged "$main" --shell --format='
set -eu
ref=%(refname)
sha=%(objectname)
shortref=%(refname:short)
shortsha=%(objectname:short)
if ! echo "$heads" | grep -Fq "$ref"; then
    git update-ref -d "$ref" "$sha"
    echo "Deleted $shortref ($shortsha)"
fi
')"
