#!/usr/bin/python
import os
import subprocess

from gi.repository import GLib, NMClient
def active_connections_changed(*args):
    for sock in os.listdir(os.path.expanduser('~/.ssh/sockets')):
        dest, port = sock.rsplit(":", 2)
        subprocess.call(['ssh', '-O', 'exit', '-p', port, dest])

c = NMClient.Client.new()
c.connect('notify::active-connections', active_connections_changed)
GLib.MainLoop().run()
